Month 7/step 1
chsergey80/react-stellar-burger pull request #1
Opened 2023-05-06 18:58 UTC by chsergey80

Высылаю на промежуточную проверку проект "Stellar Burger", открытый из ветки month-7/step-1.

2023-05-06 19:17 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Проект соответствует макету
- Хорошая работа с `propTypes`
- Хороший `codestyle` - ничего лишнего, избежали дублирования кода, создали универсальные функции

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В консоли есть несколько ошибок - их нужно исправить

 <img width="462" alt="Снимок экрана 2023-05-06 в 22 15 13" src="https://user-images.githubusercontent.com/60173362/236642613-628168c4-626d-48d5-9068-721b20d1afb4.png">

- Добавьте `isRequired` после функции `shape`
- элементам списка нужно задавать `key`, он помогает понять реакту, что элементы перемещаются в списке

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-06 19:17 UTC, andryxxa93 commented on src/utils/prop-types.js
> +});
**Необходимо исправить**
После закрывающей скобки функции `shape` необходимо так же ставить `isRequired`

2023-05-06 22:57 UTC, chsergey80 commented
Доброй ночи, внес правки после первого промежуточного ревью. Отправляю на второе промежуточное ревью.

2023-05-07 16:20 UTC, andryxxa93 commented
Отличная работа, промежуточная работа принята, вы можете приступать к финальной части сдачи работы!
Удачи!

2023-05-07 18:30 UTC, merged