Month 7/step 2
chsergey80/react-stellar-burger pull request #2
Opened 2023-05-10 20:35 UTC by chsergey80

Направляю проект "stellar-burger" на ревью - 1, step - 2.

2023-05-11 08:41 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализовали закрытие по ESC
- Обрабатываете ошибку запроса
- Рендерите модалку только если она нужна

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса
- Поправьте propType у `IngredientDetails`
- Передавайте в `addEventListener ` и `removeEventListener ` именованную функцию

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-11 08:41 UTC, andryxxa93 commented on src/components/app/app.jsx
> +    const getBurgrInfo = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-05-11 08:41 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        const burgerInfo = await res.json();
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-05-11 08:41 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        </main>
**Можно лучше**
Лаконичнее будет сделать так 
```
        { stateInfo.length &&
            <>
              <BurgerConstructor ingredients={stateInfo} />
              <BurgerIngredients ingredients={stateInfo} />
            </>
        }
```

2023-05-11 08:41 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.jsx
> +IngredientDetails.propTypes = {info: PropTypes.object.isRequired, onClose: PropTypes.func.isRequired};
**Необходимо исправить**
У вас уже типизирован объект ингредиента, тут его и следует использовать для пропа - `info`

2023-05-11 08:41 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +  }, [])
**Необходимо исправить**
В `addEventListener` и в `removeEventListener ` необходимо передавать именованную, а не анонимную функцию, иначе отписка не сработает.

2023-05-11 18:31 UTC, chsergey80 commented
13 commit / Исправлены замечания 1 ревью 2 этапа сдачи проекта:
              - Вынесен в отдельную функцию и отдельный файл utils/burger-api.js API запрос.
              - Добавлена проверка ответа сервера - res.ok.
              - В файле ingredient-details.jsx внесены исправления касающиеся типизации пропса info.
              - Код в модуле app.jsx касающийся вызова модулей BurgerConstructor и BurgerIngredients оптимизирован.
              - В модуле modal.jsx исправлен код, в addEventListener и в removeEventListener передана именованная функция.

2023-05-12 08:24 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-22 19:43 UTC, chsergey80 commented
Осуществляем слияние ветки main и month-7/step-2

2023-05-22 19:43 UTC, merged